# **Classification Evaluation Metrics :**


## **Confusion Matrix Table :**




**Note :**


```
# Each Row Corresponds to  "Actual class" Whereas Each Columns Corresponds to "Predicted Class"
```



**Binary Class Prediction :**

```
                       Predicted Negative               Predicted Positive

Actual Negative           True Negative                    False Positive

Actual Positive           False Negative                   True Postive
```

**Explanation**

```
# True Negative (TN)   --> The Values is Actually Negative and correctly predicted as Negative Too.

# Fasle Positive (FP)  --> The Values is Actually Negative  and incorrectly predicted as Positive.

# False Negative (FN)  --> The Values is Actually Positive and incorrectly predicted as Negative.

# True Positive  (TP)  --> The values is Actually Postive and correctly predicted as Positive Too.
```

**Multi-Class Prediction :**

```
                          Predicted Class 0    Predicted Class 1     Predicted Class 2

Actual Class 0             True 0               False 1                False 2

Actual Class 1             False 0              True 1                 False 2

Actual Class 2             False 0              False 1                True 0

```

**Explanation**

```
# Major Diagonal Values are predicted Correctly so its True 0 , 1, 2.

# Remaings are predicted Incorrectly so False Occured.

```

### **Example :**



In [ ]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix

from sklearn.preprocessing import OrdinalEncoder

import numpy as np

import pandas as pd

In [ ]:
# Data Collection

df = pd.read_csv('https://raw.githubusercontent.com/praveendecode/Datasets/main/diabetes_prediction_dataset.csv')

df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [ ]:
df.diabetes.value_counts()  # Inbalanced dataset

0    91500
1     8500
Name: diabetes, dtype: int64

In [ ]:
# Preprocessing

df.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [ ]:
enc = OrdinalEncoder()

df['gender'] = enc.fit_transform(df[['gender']])

df['smoking_history'] = enc.fit_transform(df[['smoking_history']])

In [ ]:
df

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0         0.0  80.0             0              1              4.0  25.19   
1         0.0  54.0             0              0              0.0  27.32   
2         1.0  28.0             0              0              4.0  27.32   
3         0.0  36.0             0              0              1.0  23.45   
4         1.0  76.0             1              1              1.0  20.14   
...       ...   ...           ...            ...              ...    ...   
99995     0.0  80.0             0              0              0.0  27.32   
99996     0.0   2.0             0              0              0.0  17.37   
99997     1.0  66.0             0              0              3.0  27.83   
99998     0.0  24.0             0              0              4.0  35.42   
99999     0.0  57.0             0              0              1.0  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [ ]:
# Model Train

x = df.drop('diabetes',axis=1)
y = df['diabetes']
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3)

model = LogisticRegression().fit(x_train,y_train) # trained with x(Independent) , y(depedent) traning data

# Model Prediction

y_pred = model.predict(x_test)

In [ ]:
# Model Accuracy score

from sklearn.metrics import accuracy_score

result = accuracy_score(y_test,y_pred)

result

In [ ]:
# Confusion Metrics

from sklearn.metrics import  confusion_matrix


cm = confusion_matrix(y_test,y_pred)

cm_df =  pd.DataFrame(cm,columns=['Predicted No Diabetes','Predicted Diabetes'])

cm_df.rename(index={0:'Actual No Diabetes',1:'Actual Diabetes'},inplace=True)

cm_df

Predicted No Diabetes  Predicted Diabetes
Actual No Diabetes                  27185                 276
Actual Diabetes                       975                1564

**Explanation:**



```
# Here Negative = No Diabetes and Positive = Diabetes
```

```
# Actual No Diabetes data is 91500 and Actuall  Diabetes data is 8500.

1. True Negative :  27185 data predicted as Non Diabetes out of 91500 Non diabetes.

2. False Positive : 276 data incorrectly predicted  as  diabetes but actually its non diabetes.

3. False Negative : 975	 data incorrectly predicted as No diabetes but actually its diabetes.

4. True positive : 1564 data correcty predicted as diabetes and its actually diabetes
```



In [ ]:
df['diabetes'].value_counts() # Actual Values

0    91500
1     8500
Name: diabetes, dtype: int64

## **Accuracy :**






**Goal Of Metric**
```
#  Assess The Model's Overall Performance.
```


**Why is it used ?**
```
# It  Provides the measure that how well the model is performing in overall correctness.
```

**Formula**

```
     Accuracy = No of Correct Predictions(True Positive + True Negative) / Total No Of Instances

     # Percentage of Correctly Predicted Instances(Both True Positive and True negative) to the  Overall Instances in dataset.

```

**Note :**
```
     -->  Correctness measure ranging from 0 (No Correct predictions) to 1 (All predictions are coorect).


     -->  Advisable to use this metric  in  balanced data.
```
**Example :**

```
  # Spam Detection Dataset : Where Spam Emails are Positive Predictions , Non-Spam are Negative Prediction.

  # Here we will get the accuracy of both Spam and Non-Spam emails predicton correctness  from the total data of emails in dataset.

  Note :
     --> Positive and Negative prediction names are we used to classify the predicting terms in a dataset and its generalized.
     --> We can give any class names instead of positive and negative  e.g: 0 and 1  (or) apple and orange (or)  bus and car etc....
        
```

## **Precision :**



**Goal Of Metric**
```
#  Assess The True Positive Preditions of the model. (Accuracy of True positive Predictions )

#  Minimises False Positives
```


**Why is it used ?**
```
# It  Provides the measure that represents  how well the model performs when predictiong True positive class.
```

**Formula**

```
     Precision = True Positives / Overall  Positive Predictions(True Positives + False Positives)  

     # Results a Percentage as output that represents how well the model performing when predicting the True positive Values.

```


```
Note :

     -->  Correctness measure ranging from 0 (Not True predictions) to 1 (All predictions are correct/True).


     --> We can use it in both balanced and unbalanced dataset .
```


**Example By Praveen**



```
Example : Precision (Spam Detection)


        --> Here    Spam = positive    and    Non-Spam = Negative


Total Data in dataset : 100 emails --> 70 spam emails , 30 non-spam email in Model Traning .


While Model Prediction :


                           Predicted Spam                 Predicted Non-Spam

  Actual spam             True Positive(70)                False Negative(0)

  Actual Non Spam         False positive(10)               True Negative(20)


------------
Explanation :
------------

#  Assume,  Here we have 100  sample email in our dataset where the actually spam email is 70 (True Positive) ,  extra 10 predicted as spam too but it actaully non spam email acc to our table.


#  This Will Mislead Normal Content into Spam


# here we Using Precision to calculate the Percentage of True positive predictions to minimises the False positive predictions.


                ==> Precision =  70  / ( 70 + 10 )  = 70/80 = 0.875


-----------
Conclusion :
-----------
   # This indicates model predicting Performace is 87.5% while predicting the True Positives(Spam Emails)

```

```
Note :

     -->  Correctness measure ranging from 0 (Not True predictions) to 1 (All predictions are correct/True).


     --> We can use it in both balanced and unbalanced dataset .
```



## **Recall :**


**Goal Of Metric**
```
# Assess the ability of the model to capture all relevant positive instances.

# Minimize False Negatives.
```


**Why is it used ?**
```
# Provides a measure of how well the model performs when ensuring that positive instances are not missed.
```

**Formula**

```
     Recall = True Positives / (True Positives + False Negatives)

     # Results in a percentage that represents how well the model is capturing all true positive values.

```

**Example By Praveen**


```
Example  : Recall (Spam Detection)

        --> Here    Spam = positive    and    Non-Spam = Negative

Total Data in dataset: 100 emails --> 70 spam emails, 30 non-spam emails in Model Training.

While Model Prediction:

                           Predicted Spam               Predicted Non-Spam

  Actual spam             True Positive(70)                False Negative(0)

  Actual Non-Spam         False Positive(10)               True Negative(20)

------------
Explanation:
------------

# Assume, Here we have 100 sample emails in our dataset where actually spam emails are 70 (True Positives), but none of them were missed (False Negatives = 0).

# This ensures that all spam emails are correctly identified, minimizing the risk of missing any.

# Using Recall, we calculate the percentage of true positive predictions, focusing on capturing all true positive values.

                ==> Recall = 70 / (70 + 0) = 70/70 = 1.0

-----------
Conclusion:
-----------
   # This indicates that the model's performance in capturing all true positive values (spam emails) is perfect, with a recall of 100%.


```

```
Note :

     -->  Correctness measure ranging from 0 (Not True predictions) to 1 (All predictions are correct/True).


     --> We can use it in both balanced and unbalanced dataset .
```

